# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fpmk8BUmUDjrPrbJMpXNXYXlU6Q3zVUc
"""

a= input()
if a == '1':
 print ("январь")
elif a =='2':
  print("февраль")
elif a == "3":
  print("март")
elif a == '4':
  print("апрель")
elif a == '5':
  print("май")
elif a == '6':
  print("июнь")
elif a == '7':
  print("июль")
elif a == '8':
  print("август")
elif a == '9':
  print("сентябрь")
elif a == '10':
  print("октябрь")
elif a == '11':
  print("ноябрь")
elif a == '12':
  print("декабрь")

"""# Новый раздел"""

a= int(input())
if a % 2 == 0:
 print("четное")
else:
 print("нечетное")

"""# Новый раздел"""

N= int(input())
if N > 40:
  print("stonks")
else:
  print("not stonks")

"""# Новый раздел"""

Z= int(input("Введите кол-во дней."))
if Z > 365:
  print ("True")
else:
   print ("False")

"""# Новый раздел"""

n= int(input())
if n > 1:
  for i in range (1, n-1):
      if n % i == 0:
        print(True)
else:
  print(False)

"""# Новый раздел"""

a= int(input())
b= int(input())
if a * 3.6 > b  or b in float(range(-138/2)**1.3,abs((-69/28**5.1)*4)):
  temp= a
  a= b
  b= temp
  print(a,b)
else:
  print (a,b)

"""# Новый раздел"""

s = set()
for i in range(5):
    x = int(input())
    s.add(x)

even = 0
neg_num = 0
v_promezhutke = 0
if len(s) == 5:
    for i in s:
        even += (i % 2 == 0)
        neg_num += (i < 0)
        v_promezhutke += (i in range(-256, 1025))

print(even, neg_num, v_promezhutke)

"""# Новый раздел"""

a= int (input())
b= int (input())
c= int (input())
s= ((a**2 + b**3)/c+3)/4
if s % 2 == 0:
  print("ответ четный")
else:
  print("ответ нечетный")
print(s)